In [1]:
from sklearn.linear_model import LogisticRegression

In [2]:
from keras.datasets import mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()

In [3]:
x_train.shape


(60000, 28, 28)

In [4]:
x_test.shape

(10000, 28, 28)

In [5]:
y_train[0:10]

array([5, 0, 4, 1, 9, 2, 1, 3, 1, 4], dtype=uint8)

In [6]:
#we create new variables that contain only zeros and ones.
x_train_binary= x_train[(y_train==0) | (y_train==1)]
y_train_binary= y_train[(y_train==0) | (y_train==1)]

#Let’s check the shape of the new variables.
x_train_binary.shape

(12665, 28, 28)

In [7]:
print(y_train[0:10]) 
print(y_train_binary[0:10])

[5 0 4 1 9 2 1 3 1 4]
[0 1 1 1 1 0 1 1 0 0]


In [8]:
#we need to flatten data into two dimensions only: (28 * 28 = 784).

x_train_final = x_train_binary.reshape((-1, 784))
x_train_final.shape

(12665, 784)

In [9]:
#A similar sequence of operations we perform for the test set.

x_test_binary= x_test[(y_test==0) | (y_test==1)]
y_test_binary= y_test[(y_test==0) | (y_test==1)]
x_test_binary.shape

(2115, 28, 28)

In [10]:
x_test_final = x_test_binary.reshape((-1, 784))
x_test_final.shape

(2115, 784)

In [11]:
#The last element of data preprocessing is their normalization.

x_train_final = x_train_final / 255
x_test_final = x_test_final / 255

In [12]:
model=LogisticRegression()


In [13]:
model.fit(x_train_final,y_train_binary)  

LogisticRegression()

In [14]:
y_pred= model.predict(x_test_final)

In [15]:
y_pred

array([1, 0, 1, ..., 1, 0, 1], dtype=uint8)

In [16]:
from sklearn.metrics import accuracy_score


In [17]:
accuracy_score(y_test_binary,y_pred)*100

99.95271867612293